### ISSUE TITLE
required a higher minimum deployment target

### ISSUE THREAD

**Issue by wow-such-amazing** [develapps/movver-ios#1]
when trying to 'pod install' i get such error

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Movver` required by `Podfile`

Specs satisfying the `Movver` dependency were found, but they required a higher minimum deployment target.
```
Maybe that's because in your podspec file 
`s.ios.deployment_target = '10.1'`

Does your pod really need such high minimum deployment target?

**Comment by pabloromeu** [comment]
You are right @crabman448 10.1 is not really needed. I have pushed it down to 9.0. Check version 2.1.2

**Comment by wow-such-amazing** [comment]
@pabloromeu i can even compile your pod for ios 8. Only UIStackView requires ios 9, not MOVVER. Would be great if you'll fix it :)

**Comment by pabloromeu** [comment]
Ok did it! ;) version 2.1.3

**Comment by wow-such-amazing** [comment]
@pabloromeu Thanks!)
